//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegradorBlog.Datos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posteos
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Resumen { get; set; }
        public string Contenido { get; set; }
        public string Autor { get; set; }
        public System.DateTime FechaDePublicacion { get; set; }
        public bool Destacada { get; set; }
        public Nullable<int> Categoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
