--CREATE DATABASE Digitalers2021

USE Digitalers2021

CREATE TABLE MiPrimerTabla(
	ID INT
)

CREATE TABLE Personas (
	LEGAJO INT IDENTITY,
	DNI INT NOT NULL,
	APELLIDOS NVARCHAR(40) NOT NULL,
	NOMBRES NVARCHAR (40) NOT NULL,
	APODO NVARCHAR(20) NOT NULL,
	ACTIVO BIT NOT NULL,
	FECHA_DE_NACIMIENTO DATE,
	PRIMARY KEY(LEGAJO)
)

-- DROP TABLE Personas;
/*

*/

INSERT INTO Personas (DNI,APELLIDOS,NOMBRES,APODO,ACTIVO) VALUES
(141203981,'Suarez','Julian','Juli',1)

SELECT dni documento,APELLIDOS FROM Personas
WHERE dni = (5233 + 1) or dni = 123124312